/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Close: typeof import('./lib/components/Icon/Close/index.vue')['default']
    Coin: typeof import('./lib/components/Icon/Coin/index.vue')['default']
    CountDown: typeof import('./lib/components/CountDown/index.vue')['default']
    DataEmpty: typeof import('./lib/components/Icon/DataEmpty/index.vue')['default']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    Female: typeof import('./lib/components/Icon/Female/index.vue')['default']
    I18nTr: typeof import('./lib/components/CountDown/i18n-tr.vue')['default']
    IconArrowBlack: typeof import('./svg/icon-arrow-black.svg')['default']
    IconArrowWhite: typeof import('./svg/icon-arrow-white.svg')['default']
    IconClipboard: typeof import('./svg/icon-clipboard.svg')['default']
    IconCloseGray: typeof import('./svg/icon-close-gray.svg')['default']
    IconCloseWhite: typeof import('./svg/icon-close-white.svg')['default']
    IconCoin: typeof import('./svg/icon-coin.svg')['default']
    IconDiamond: typeof import('./svg/icon-diamond.svg')['default']
    IconDollar: typeof import('./svg/icon-dollar.svg')['default']
    IconDoubleArrow: typeof import('./svg/icon-double-arrow.svg')['default']
    IconDownload: typeof import('./svg/icon-download.svg')['default']
    IconEditPen: typeof import('./svg/icon-edit-pen.svg')['default']
    IconError: typeof import('./svg/icon-error.svg')['default']
    IconFollow: typeof import('./svg/icon-follow.svg')['default']
    IconGarbage: typeof import('./svg/icon-garbage.svg')['default']
    IconInfoWhite: typeof import('./svg/icon-info-white.svg')['default']
    IconIntegral: typeof import('./svg/icon-integral.svg')['default']
    IconLightning: typeof import('./svg/icon-lightning.svg')['default']
    IconMoreBlack: typeof import('./svg/icon-more-black.svg')['default']
    IconMsnWhite: typeof import('./svg/icon-msn-white.svg')['default']
    IconRefresh: typeof import('./svg/icon-refresh.svg')['default']
    IconSticker: typeof import('./svg/icon-sticker.svg')['default']
    IconSuccess: typeof import('./svg/icon-success.svg')['default']
    IconTreasureScore: typeof import('./svg/icon-treasure-score.svg')['default']
    IconTriangleBlack: typeof import('./svg/icon-triangle-black.svg')['default']
    IconTriangleWhite: typeof import('./svg/icon-triangle-white.svg')['default']
    Loading: typeof import('./lib/components/Loading/index.vue')['default']
    Lottie: typeof import('./lib/components/Lottie/index.vue')['default']
    Male: typeof import('./lib/components/Icon/Male/index.vue')['default']
    MediaPlayer: typeof import('./lib/components/MediaPlayer/index.vue')['default']
    Modal: typeof import('./lib/components/Modal/index.vue')['default']
    PageHeader: typeof import('./lib/components/PageHeader/index.vue')['default']
    Question: typeof import('./lib/components/Icon/Question/index.vue')['default']
    ResizeImage: typeof import('./lib/components/ResizeImage/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollTab: typeof import('./lib/components/ScrollTab/index.vue')['default']
    ScrollTabCol: typeof import('./lib/components/ScrollTabCol/index.vue')['default']
    Toast: typeof import('./lib/components/Toast/index.vue')['default']
    VapPlayer: typeof import('./lib/components/VapPlayer/index.vue')['default']
  }
}
