apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: ringo-web-route
spec:
  http:
    - name: ringo-web
      match:
        paths:
          - /*
        hosts:
          - sandbox.ringo.cool
      backends:
        - serviceName: ringo-web
          servicePort: 80
