apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: telo-web-route
spec:
  http:
    - name: telo-web
      match:
        paths:
          - /*
        hosts:
          - sandbox.telo.cool
      backends:
        - serviceName: telo-web
          servicePort: 80
