apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: telo-web-route
  namespace: telo-production
  annotations:
    k8s.apisix.apache.org/upstream-scheme: http
spec:
  http:
    - name: telo-web
      match:
        paths:
          - /*
        hosts:
          - teloapp.net
      backends:
        - serviceName: telo-web
          servicePort: 80
      plugins:
        - name: redirect
          enable: true
          config:
            http_to_https: true
