name: Pull Request Auto Merge To Dev
on:
  # 推送代码后触发
  pull_request:
    types:
      - closed
    branches:
      - stable

jobs:
  merge_pull_request:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Merge
        run: |
          git config --global user.name 'Github Bot'
          git config --global user.email '<>'
          git pull --unshallow
          git checkout -b staging origin/staging
          git merge --no-edit ${{ github.base_ref }}
          git push origin staging
