apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: ringo-web-route
spec:
  http:
  - name: ringo-web
    match:
      paths:
      - /*
      hosts:
      - ringo.staging.voya.world
    backends:
    - serviceName: ringo-web
      servicePort: 80
